version: '3'
services:
  app:
    image: ee_capture_dashboard
    restart: always
    build: .
    volumes:
      - .:/app/
      - dependencies:/app/node_modules
    working_dir: /app
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    command: npm start
volumes:
  dependencies: